config/routes.rb
Rails.application.routes.draw do

  get 'admins/admin_list'
  post 'bookings/search'  => 'bookings#search'
  post '/rooms/search'  => 'rooms#search'
  # get '/rooms/search'  => 'rooms#search'


  get 'bookings/send_email'
  post 'bookings/send_email'
  resources :bookings
  resources :rooms
  resources :admins
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'helper_pages/home'
  get 'helper_pages/about'
  get 'helper_pages/contact'
  get 'sessions/new_admin'
  get 'sessions/new_member'

  root 'helper_pages#home'
  get 'about'    => 'helper_pages#about'
  get 'contact'  => 'helper_pages#contact'
  get 'signup'   => 'members#new'
  post 'signup'  => 'members#create'
  get 'new_admin_create'   => 'admins#new'
  post 'new_admin_create'  => 'admins#create'

  get  'admin_login'   => 'sessions#new_admin'
  post 'admin_login'   => 'sessions#create_admin'

  get  'member_login'  => 'sessions#new_member'
  post 'member_login'  => 'sessions#create_member'

  delete 'logout'      => 'sessions#destroy'

  get 'members/edit'
  get 'members/update'

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings, :dependent => :delete_all

  validates :room_number, :presence=>true, :uniqueness => true
  validates :size, :presence=>true
  validates :building, :presence=>true

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:search]
  include SessionsHelper
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def search


    #{"slot_start"=>"1000-01-01 00:00:00 -0456", "room_id"=>"1", "member_id"=>"1"}

    newparams = params[:params]

    @rooms = query = Room.all
    if(newparams[:room_number] != "all")
      @rooms = query.where(room_number: newparams[:room_number])
    end
    if(newparams[:size] != "all")
      @rooms = query.where( size: newparams[:size] );
    end
    if(newparams[:building] != "all")
      @rooms = query.where(building: newparams[:building]);
    end
=begin
    if(newparams[:status] != "all")
      debugger
      rooms = Booking.where(slot_start: (Time.now - 3.hours)..Time.now).select(:room_id).distinct
      rooms = rooms.collect{|x| x.room_id}
      @rooms = query.where.not(building: rooms);
    end
=end


    if(@rooms == nil)
      @rooms = []
    end

=begin

    key= params[:search][:keyword]
    unfiltered_books = Book.lookup(key)
    @books = unfiltered_books
    unless params[:search][:checked_out] == "all"
      @books = unfiltered_books.select {|b| b.checked_out.to_s == params[:search][:checked_out]}
    end
    @search_params = {}
    @search_params[:keyword] = params[:search][:keyword]
    @search_params[:checked_out] = params[:search][:checked_out]

=end
    #@bookings = Booking.all
    render 'index'
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def is_member_viewing_this?
    @memberViewing  = false
    if(current_member)
      @memberViewing  = true
    end
  end

  def is_admin_viewing_this?
    @adminViewing  = false
    if(current_admin)
      @adminViewing  = true
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      logger.fatal "#{params}"
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_number, :size, :building)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <table>
  <tr>
    <th><div class="field">
    <%= f.label :room_number %>
    <%= f.number_field :room_number %>
  </div></th>

  <th><div class="field">
    <%= f.label :size %>
    <%= f.select :size,[['Small','small'],['Medium','medium'],['Large','large']] %>
  </div></th>

  <th><div class="field">
    <%= f.label :building %>
    <%= f.select :building,[['Hunt','Hunt'],['D.H.Hill','D.H.Hill']] %>
  </div></th>
  </tr>
    </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room, class: "btn btn-md btn-info" %> |
<%= link_to 'Back', rooms_path, class: "btn btn-md btn-info" %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<%= form_tag '/rooms/search', :method=>'post' do %>

    <div class="field">
        <%= label_tag :room_number %>
        <%= select("params", "room_number",[["all",:all]] +  Room.all.collect{ |r| [ r.room_number, r.room_number] }) %>

      <%= label_tag :size %>
      <%= select("params", "size", [["all",:all]] +  Room.all.collect{ |r| [ r.size, r.size] }.uniq{|x| x}) %>

      <%= label_tag :building %>
      <%= select("params", "building",  [["all",:all]] + Room.all.collect{ |r| [ r.building, r.building] }.uniq{|x| x} ) %>

      <%= label_tag :status %>
      <%= select("params", "status",  [["all",:all],["Available",:available]] ) %>
    </div>
    <%= submit_tag "Search", class: "btn btn-info" %>
    <br>
    <br>
<% end %>


<table>
  <thead>
    <tr>
      <th>Room number</th>
      <th>Size</th>
      <th>Building</th>
      <th></th>
      <% if admin_logged_in? %>
      <th></th>
          <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_number %></td>
        <td><%= room.size %></td>
        <td><%= room.building %></td>

        <td><%= link_to 'Show Bookings', bookings_path({room:room}), class: "btn btn-md btn-info" %></td>
        <% if admin_logged_in? %>
          <td><%= link_to 'Edit', edit_room_path(room), class: "btn btn-md btn-info" %></td>
        <% end %>
        <% if admin_logged_in? %>
          <td><%= link_to 'Delete', room, method: :delete, data: { confirm: 'All the bookings for this room will also be lost. Are you sure?' }, class: "btn btn-md btn-info" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<p></p>
<% if admin_logged_in? %>
<div class="center">
  <%= link_to 'Add a New Room', new_room_path, class: "btn btn-md btn-info"%>
</div>
<% end %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= form_for(@room) do |f| %>
    <% if @room.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

          <ul>
            <% @room.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table>
      <tr>
        <th><div class="field">
          <%= f.label :room_number %>
          <%= f.number_field :room_number %>
        </div></th>

        <th><div class="field">
          <%= f.label :size %>
          <%= f.select :size,[['Small','small'],['Medium','medium'],['Large','large']] %>
        </div></th>

        <th><div class="field">
          <%= f.label :building %>
          <%= f.select :building,[['Hunt','hunt'],['D.H.Hill','hill']] %>
        </div></th>
      </tr>
    </table>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', rooms_path, class: "btn btn-md btn-info" %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room number:</strong>
  <%= @room.room_number %>
</p>

<p>
  <strong>Size:</strong>
  <%= @room.size %>
</p>

<p>
  <strong>Building:</strong>
  <%= @room.building %>
</p>

<% if admin_logged_in? %>
<%= link_to 'Edit', edit_room_path(@room), class: "btn btn-md btn-info" %>
    <% end %>

<br>
<br>
  <%= link_to 'Back', rooms_path, class: "btn btn-md btn-info" %>