config/routes.rb
Rails.application.routes.draw do

  get 'admins/admin_list'
  post 'bookings/search'  => 'bookings#search'
  post '/rooms/search'  => 'rooms#search'
  # get '/rooms/search'  => 'rooms#search'


  get 'bookings/send_email'
  post 'bookings/send_email'
  resources :bookings
  resources :rooms
  resources :admins
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'helper_pages/home'
  get 'helper_pages/about'
  get 'helper_pages/contact'
  get 'sessions/new_admin'
  get 'sessions/new_member'

  root 'helper_pages#home'
  get 'about'    => 'helper_pages#about'
  get 'contact'  => 'helper_pages#contact'
  get 'signup'   => 'members#new'
  post 'signup'  => 'members#create'
  get 'new_admin_create'   => 'admins#new'
  post 'new_admin_create'  => 'admins#create'

  get  'admin_login'   => 'sessions#new_admin'
  post 'admin_login'   => 'sessions#create_admin'

  get  'member_login'  => 'sessions#new_member'
  post 'member_login'  => 'sessions#create_member'

  delete 'logout'      => 'sessions#destroy'

  get 'members/edit'
  get 'members/update'

end

app/controllers/helper_pages_controller.rb
class HelperPagesController < ApplicationController
  def home

  end

  def about
  end

  def contact
  end
end

app/views/helper_pages/about.html.erb
<h1> About us </h1>
<p>This is a website created with Ruby on Rails. It helps a library member book rooms to study.
</p>

app/views/helper_pages/contact.html.erb
<h1> Contact us - </h1>
<p>

  <br>
  Payal Chheda
  <br>
  Vaibhav Shinde
  <br>
  Harshal Gurjar
</p>

app/views/helper_pages/home.html.erb
<% if !member_logged_in? &&  !admin_logged_in?%>
    <div class="center jumbotron">
      <h1>Room Booking Ruby on Rails Application</h1>

      <br><br>
      <h2>
        This is the home page for the application.
      </h2>

      <%= link_to "Click here to signup!" , signup_path, class: "btn btn-lg btn-default" %>
    </div>

<% end %>
<% if admin_logged_in? %>
    <div class="center jumbotron">
      <h1>Welcome Admin</h1>
      <h2><%= link_to "Edit Profile",  edit_admin_path(1), class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "Manage Admins", admins_path, class: "btn btn-block btn-default" %></h2>
      <h2><%= link_to "Manage Members", members_path, class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "Manage Rooms", rooms_path, class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "Manage Bookings", bookings_path, class: "btn btn-block btn-default"%></h2>
    </div>
<% end %>
<% if member_logged_in? %>
    <div class="center jumbotron">
      <h1>Welcome to Library Room Booking System</h1>
      <h2><%= link_to "Edit Profile",  edit_member_path(current_member.id), class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "View Rooms", rooms_path, class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "Bookings", bookings_path, class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "My Booking history", bookings_path({member:current_member.id}), class: "btn btn-block btn-default"%></h2>
    </div>
<% end %>