config/routes.rb
Rails.application.routes.draw do

  get 'admins/admin_list'
  post 'bookings/search'  => 'bookings#search'
  post '/rooms/search'  => 'rooms#search'
  # get '/rooms/search'  => 'rooms#search'


  get 'bookings/send_email'
  post 'bookings/send_email'
  resources :bookings
  resources :rooms
  resources :admins
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'helper_pages/home'
  get 'helper_pages/about'
  get 'helper_pages/contact'
  get 'sessions/new_admin'
  get 'sessions/new_member'

  root 'helper_pages#home'
  get 'about'    => 'helper_pages#about'
  get 'contact'  => 'helper_pages#contact'
  get 'signup'   => 'members#new'
  post 'signup'  => 'members#create'
  get 'new_admin_create'   => 'admins#new'
  post 'new_admin_create'  => 'admins#create'

  get  'admin_login'   => 'sessions#new_admin'
  post 'admin_login'   => 'sessions#create_admin'

  get  'member_login'  => 'sessions#new_member'
  post 'member_login'  => 'sessions#create_member'

  delete 'logout'      => 'sessions#destroy'

  get 'members/edit'
  get 'members/update'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li>
        <%= link_to "Contact", contact_path %>
      </li>
      <li>
        <%= link_to "About", about_path %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Library App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <% if member_logged_in? ||  admin_logged_in?%>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
        <% else %>
            <li><%= link_to "Admin Log in", admin_login_path %></li>
            <li><%= link_to "Member Log in", member_login_path %></li>
            </ul>
        <% end %>
        <% if admin_logged_in? %>
            <!-- p> Admin logged in. </p -->
            <ul class="nav navbar-nav navbar-left">
              <li><%= link_to "List all Admins", controller: 'admins', action: 'admin_list' %></li>
              <li><%= link_to "Manage Members", members_path %></li>
              <li><%= link_to "Rooms", rooms_path %></li>
              <li><%= link_to "Manage Bookings", bookings_path %></li>
              <li><%= link_to "Edit Profile",  edit_admin_path(1)%></li>
              <!-- %= link_to "List all Admins", admins_path %></li -->
            </ul>
        <% end %>
        <% if member_logged_in? %>
            <!-- p> Member logged in. </p -->
            <ul class="nav navbar-nav navbar-left">
              <li><%= link_to "Rooms", rooms_path %></li>
              <li><%= link_to "Bookings", bookings_path %></li>
              <li><%= link_to "Edit Profile", edit_member_path(current_member.id)%></li>
              <li><%= link_to "My Booking history", bookings_path({member:current_member.id})%></li>
            </ul>
        <% end %>

        </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library Room Booking System</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>