config/routes.rb
Rails.application.routes.draw do

  get 'admins/admin_list'
  post 'bookings/search'  => 'bookings#search'
  post '/rooms/search'  => 'rooms#search'
  # get '/rooms/search'  => 'rooms#search'


  get 'bookings/send_email'
  post 'bookings/send_email'
  resources :bookings
  resources :rooms
  resources :admins
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'helper_pages/home'
  get 'helper_pages/about'
  get 'helper_pages/contact'
  get 'sessions/new_admin'
  get 'sessions/new_member'

  root 'helper_pages#home'
  get 'about'    => 'helper_pages#about'
  get 'contact'  => 'helper_pages#contact'
  get 'signup'   => 'members#new'
  post 'signup'  => 'members#create'
  get 'new_admin_create'   => 'admins#new'
  post 'new_admin_create'  => 'admins#create'

  get  'admin_login'   => 'sessions#new_admin'
  post 'admin_login'   => 'sessions#create_admin'

  get  'member_login'  => 'sessions#new_member'
  post 'member_login'  => 'sessions#create_member'

  delete 'logout'      => 'sessions#destroy'

  get 'members/edit'
  get 'members/update'

end

app/models/member.rb
class Member < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true, length: { minimum: 6 }
  has_many :bookings, :dependent => :delete_all

  def authenticated?
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  #before_action :require_member_login, only: [:index, :destroy]
  #before_action :require_admin_login, only: [:index, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    @member=Member.find(params[:id])
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member=Member.find(params[:id])
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def require_admin_login
      unless admin_logged_in?
        flash[:error] = "Please Log in to view this page"
        redirect_to admin_login_path
      end
    end

    def require_member_login
      unless member_logged_in?
        flash[:error] = "Please Log in to view this page"
        redirect_to member_login_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(member) do |f| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@member) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-info" %>
    <% end %>

  </div>
</div>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <% if admin_logged_in? %>
      <th colspan="4"></th>
      <% else %>
      <th></th>
       <% end %>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>

        <td><%= link_to 'Show', member, class: "btn btn-md btn-info" %></td>

        <% if admin_logged_in? %>
            <td><%= link_to 'Show Booking History', bookings_path({member:member}), class: "btn btn-md btn-info" %></td>
            <td><%= link_to 'Edit', edit_member_path(member), class: "btn btn-md btn-info" %></td>
        <td><%= link_to 'Delete', member, method: :delete, data: { confirm: 'All the bookings made by this member will also be lost. Are you sure? ' } ,class: "btn btn-md btn-info"%></td>
            <% end %>

      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if admin_logged_in? %>
    <div class="center">
      <%= link_to 'Add a New Member', new_member_path, class: "btn btn-md btn-info"%>
    </div>
<% end %>
<br>

app/views/members/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@member, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Password Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account" %>
    <% end %>
  </div>
</div>

app/views/members/show.html.erb
<h1> Library Member Details </h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Name:</th>
    <td><%= @member.name %></td>
  </tr>
  <tr>
    <th>Email:</th>
  <td><%= @member.email %></td>
</table>

<br>
<br>
<% if !admin_logged_in? %>
<div class="center">
<%= link_to "log in", member_login_path, class: "btn btn-md btn-info" %>
</div>
<%end%>
<% if admin_logged_in? %>
    <div class="center">
      <%= link_to "back", members_path, class: "btn btn-md btn-info" %>
    </div>
<%end%>